
title: overtrue - 安正超博客
url: http://overtrue.me
description: 安正超，软件工程师，从事web相关的开发工作。开源爱好者，Laravel贡献者，GitHub:https://github.com/overtrue。
keywords: Laravel,Laravel教程,Laravel安装,Laravel视频,安正超,overtrue,Pinyin,汉字转拼音

timezone:    PRC
encoding:    UTF-8

future:      true
highlighter: pygments

baseurl:  http://overtrue.me
permalink:     date
paginate_path: 'page:num'

markdown:      kramdown
markdown_ext:  markdown,md
textile_ext:   textile
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: true
coderay:
  coderay_wrap: div
  coderay_line_numbers: nil
  coderay_tab_width: 4
  coderay_bold_every: 10
  coderay_css: class
excerpt_separator: "\n\n"